baseURL = "http://www.p2.work/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "en-us"
languageCode = "en-us"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Power 2 work"
# 更改使用 Hugo 构建网站时使用的默认主题
enableEmoji = true
theme = "LoveIt"

[params]
# LoveIt 主题版本
version = "0.2.X"

[menu]

[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
name = "Posts"
post = ""
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3

# Hugo 解析文档的配置
[markup]

# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

[params.page.comment]
enable = true

# Gitalk 评论系统设置
[params.page.comment.gitalk]
# LoveIt 新增 | 0.1.1
clientId = "22463c8f865044618cf7"
clientSecret = "5eecaead798bce0e49cc8ddee2e47ec780ebd402"
enable = false
owner = "grapehunter"
repo = "power2work"
[params.page.comment.utterances]
enable = true

darkTheme = "github-dark"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
# owner/repo
repo = "grapehunter/power2work"

[outputs]
home = ["HTML", "RSS", "JSON"]
